### ISSUE TITLE
How to specify the API limitation 

### ISSUE THREAD

**Issue by tgarm** [Frefreak/certbot-dns-tencentcloud#1]
It's just a help request and perhaps document update request.
In the Tencent Cloud (non primary) API user creation panel, there is no category named with *DNS* or *解析*. And I can't find any category name looks like related to the DNS control.

Would you mind add this category name into the README document? 
Thank you in advance!

**Comment by Frefreak** [comment]
Sorry for the late response. As far as I know there's currently no specific strategy related to DNS resolution, so actually our team is using a very high privileged api key which has "QCloudResourceFullAccess" strategy bind to it. We will try to contact the people on tencent cloud to support a rather limited strategy corresponding to only "DNS resolution" in the future.
Thanks for you suggestion.
