### ISSUE TITLE
certbot renew failed

### ISSUE THREAD

**Issue by hhucqian** [Frefreak/certbot-dns-tencentcloud#2]
try to run `certbot renew --dry-run  --dns-tencentcloud-credentials /root/tencentcloud.ini` , get error:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/mydomain.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Simulating renewal of an existing certificate for mydomain.com and *.mydomain.com
Waiting 10 seconds for DNS changes to propagate

Certbot failed to authenticate some domains (authenticator: dns-tencentcloud). The Certificate Authority reported these problems:
  Domain: mydomain.com
  Type:   unauthorized
  Detail: Incorrect TXT record "e7Z_9OzmNSRxhP08YRIWy6bA_4aG0_U9sfW_aHY3ssU" found at _acme-challenge.mydomain.com

```

1. 申请证书成功
2. TXT也设置成功
3. TXT 和日志中显示的一致

**Comment by Frefreak** [comment]
I observe that if renewing multiple domain certs without specifying authenticator (`-a`), some or all would failed. Could you please try specifying the authenticator? i.e. for relatively new certbot version:
```
sudo certbot renew --dry-run --non-interactive -a dns-tencentcloud --dns-tencentcloud-credentials /path/to/cred.ini
```
with cred.ini content looks like:
```
dns_tencentcloud_secret_id = xxx
dns_tencentcloud_secret_key = yyy
```

**Comment by hhucqian** [comment]
I have 4 SSL certificate, a.abc.com | b.abc.com | c.abc.com | *.abc.com abc.com
When I run 

```bash
sudo certbot renew --dry-run --non-interactive -a dns-tencentcloud --dns-tencentcloud-credentials /path/to/cred.ini
```

a.abc.com | b.abc.com | c.abc.com get error :

```
Simulating renewal of an existing certificate for a.abc.com
Encountered exception during recovery: certbot_dns_tencentcloud.certbot_tencentcloud_plugins.APIException: (8)服务内部错误，请稍后重试或联系客服人员解决。
Failed to renew certificate a.abc.com with error: (8)服务内部错误，请稍后重试或联系客服人员解决。
```

and *.abc.com abc.com get error :

```
Certbot failed to authenticate some domains (authenticator: dns-tencentcloud). The Certificate Authority reported these problems:
  Domain: abc.com
  Type:   unauthorized
  Detail: Incorrect TXT record "MIHY_wZD-uxVN8fz2WAUb0ujMd1ENsdMlgTDhSn5HX0" found at _acme-challenge.abc.com
```

 When I run 

```bash
sudo certbot renew --dry-run --non-interactive  --dns-tencentcloud-credentials /path/to/cred.ini
```

only *.abc.com abc.com get the same error above.

----

我总共有4个域名，三个二级域名，一个通配符域名。加上`-a dns-tencentcloud`之后，三个二级域名都报错了（不加不报错），但是通配符域名加不加都报同样的错误。

总的来说，加上`-a dns-tencentcloud`并没有解决这个问题，反而会和非通配符域名产生干扰。

 **注**：我第一次提这个issue的时候，只有通配符域名，还没有添加那三个二级域名。

**Comment by hhucqian** [comment]
I have 4 SSL certificate, a.abc.com | b.abc.com | c.abc.com | *.abc.com abc.com
When I run 

```bash
sudo certbot renew --dry-run --non-interactive -a dns-tencentcloud --dns-tencentcloud-credentials /path/to/cred.ini
```

a.abc.com | b.abc.com | c.abc.com get error :

```
Simulating renewal of an existing certificate for a.abc.com
Encountered exception during recovery: certbot_dns_tencentcloud.certbot_tencentcloud_plugins.APIException: (8)服务内部错误，请稍后重试或联系客服人员解决。
Failed to renew certificate a.abc.com with error: (8)服务内部错误，请稍后重试或联系客服人员解决。
```

and *.abc.com abc.com get error :

```
Certbot failed to authenticate some domains (authenticator: dns-tencentcloud). The Certificate Authority reported these problems:
  Domain: abc.com
  Type:   unauthorized
  Detail: Incorrect TXT record "MIHY_wZD-uxVN8fz2WAUb0ujMd1ENsdMlgTDhSn5HX0" found at _acme-challenge.abc.com
```

 When I run 

```bash
sudo certbot renew --dry-run --non-interactive  --dns-tencentcloud-credentials /path/to/cred.ini
```

only *.abc.com abc.com get the same error above.

----

我总共有4个域名，三个二级域名，一个通配符域名。加上`-a dns-tencentcloud`之后，三个二级域名都报错了（不加不报错），但是通配符域名加不加都报同样的错误。

**Comment by Frefreak** [comment]
From your description I suspect the problem might be related to the overlapping between those `xxx.abc.com` and `*.abc.com` domains, however I'm not very sure about this. I would suggest try to renew them one by one and see if the problems persist:

invoke like this:
```sh
sudo certbot certonly --dry-run --non-interactive --dns-tencentcloud-credentials ./cred.ini  -a dns-tencentcloud -d <domain>
```

However if you can provides some api call detail(maybe by setting up a proxy) or some debug print (this requires modify the code and install a local development version `sudo pip install .`, but the code itself should be easy to understand) we can look into the problem in details. Sorry for you inconvenience.

EDIT:
also make sure you are 
- using the latest certbot (in fact as long as the version is not too old everything should be fine)
- your api id/secret has sufficient permission to query/modify the dns record.

**Comment by hhucqian** [comment]
step1:
```
certbot revoke --cert-name abc.com
```
and delete all related certificate.

step2:
```
certbot certonly  -a dns-tencentcloud  -d *.abc.com --dns-tencentcloud-credentials /root/tencentcloud.ini
```

step3:
```
certbot renew --dry-run
```
all  succeeded

It seems like `certbot certonly` can only have one `-d`

step4:
```
certbot certonly  -a dns-tencentcloud  -d abc.com --dns-tencentcloud-credentials /root/tencentcloud.ini
```

step5:
```
certbot renew --dry-run
```

abc.com success and *.abc.com failed

It seems like abc.com and *.abc.com can't exist at the same time

---

另外关于权限的问题，腾讯好像跟新了接口，目前QCloudCNSFullAccess 找不到了，目前只能临时给QCloudResourceFullAccess。

如果你感兴趣的话，可以联系我，直接去我服务器上调试

**Comment by Frefreak** [comment]
So now both _a.abc.com_ and _abc.com_ has certs now, can you try to use `certonly` to renew them and see what happens? `certonly` actually can be used just like `renew`, but one domain at a time (via `-d`) and is the way I use to renew my domain certs.
For the problems you describe I will find some time to get a test domain and test it.

**Comment by hhucqian** [comment]
```
certbot renew --force-renewal --cert-name  abc.com-0001
certbot renew --force-renewal --cert-name  abc.com

certbot certonly -d  abc.com
certbot certonly -d  *.abc.com
```
all these 4 command success.

**Comment by Frefreak** [comment]
OK, so one at a time seems to work fine. I will left this open until I found the causes of your reported problems.

**Comment by Frefreak** [comment]
The problem is because of the the incorrect handling logic when determining base domain name (that is, it can't find the record of an invalid domain). Please try with the new version (1.1.0)

**Comment by hhucqian** [comment]
```
certbot certonly  -a dns-tencentcloud -d abc.com -d *.abc.com --dns-tencentcloud-credentials /root/tencentcloud.ini
```
`certbot renew --dry-run` failed

Unfortunately， I get error: `There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours，...`  I can't do other test.

**Comment by Frefreak** [comment]
That appears to be the [rate limit](https://letsencrypt.org/docs/rate-limits/#:~:text=exceeding%20the%20duplicate%20certificate%20limit%20is%20reported%20with%20the%20error%20message%20too%20many%20certificates%20already%20issued%20for%20exact%20set%20of%20domains), however if you are using `--dry-run`, certbot should be requesting against the staging env and the message should not appear. I assume the error message is for the `certonly` command? What about adding `--dry-run` to `certonly`? And is there any error message relating to `renew --dry-run`?

**Comment by hhucqian** [comment]
```
certbot certonly  -a dns-tencentcloud -d abc.com -d *.abc.com --dns-tencentcloud-credentials /root/tencentcloud.ini
```
the above command finished success and `certbot renew --dry-run` failed withing error message like this:
```
Certbot failed to authenticate some domains (authenticator: dns-tencentcloud). The Certificate Authority reported these problems:
  Domain: abc.com
  Type:   unauthorized
  Detail: Incorrect TXT record "MIHY_wZD-uxVN8fz2WAUb0ujMd1ENsdMlgTDhSn5HX0" found at _acme-challenge.abc.com
```

When I try to do some other test, I hit the rate limit.

In order to do test in different conditions, I need to delete certificate.
adding --dry-run to certonly will not save certificate locally. With out local saved certificate, I can't run renew command.

**Comment by Frefreak** [comment]
To make it clear, the original bug happens when you try to get a cert for `asdf.abc.com` when you are the owner of `abc.com`,  the code would try to query the record list of `asdf.abc.com` which will result an failure. So in fact both `certonly` and `renew` would fail for `asdf.abc.com`. (The current version will try to get records for `abc.com`, `asdf.abc.com`... until the `RecordList` api returns successfully.)

If I understand correctly you can use `certonly` to get certs, but when trying to renew it fails with the "Incorrect TXT record" message. After you deleted the certs now you can't get new cert anymore. The "Incorrect TXT record" does seems weird and unexpected. In this case I would still recommend to run `certonly --dry-run` several times for the failed domain to see if it happens every time or occasionally. (From the plugins point of view `certonly` and `renew` does the exact same thing, if certonly fails, renew would also fails).

**Comment by Frefreak** [comment]
If txt records error does happen, can you please also observe the record list during the process? Also you can query the TXT record directly during the default wait time of 10 seconds.
```sh
dig TXT _acme-challenge.abc.com
# or drill
```
and of course substitute `abc.com` with your real domain.

**Comment by hhucqian** [comment]
I chacked the operation log in DNSPOD, I think TXT record is correctly setted.
And the error message shows that TXT record is setted and queried correctly .

**Comment by Frefreak** [comment]
> Certbot failed to authenticate some domains (authenticator: dns-tencentcloud). The Certificate Authority reported these problems:
  Domain: abc.com
  Type:   unauthorized
  Detail: Incorrect TXT record "MIHY_wZD-uxVN8fz2WAUb0ujMd1ENsdMlgTDhSn5HX0" found at _acme-challenge.abc.com

Does this error still persist?

**Comment by hhucqian** [comment]
yes!  same error with different  TXT record

**Comment by Frefreak** [comment]
I'm not sure what would be the problems. For all the times I tested this only happened one time. The only thing I can think of right now is to try to make the wait time longer by using `--dns-tencentcloud-propagation-seconds` and see if that helps.

**Comment by hhucqian** [comment]
I have tried to make wait time to 40s, this make no sense

**Comment by hhucqian** [comment]
The problem happened every time. So I suggest that you can test in my server.

**Comment by Frefreak** [comment]
OK, I have sent you an email talking about this.

**Comment by Frefreak** [comment]
For future visitors:

The problem comes in two aspect.

### certonly -d `*.abc.com` -d `abc.com` failed

In this case two txt records for the same record are expected to check, i.e. `_acme-challenge.abc.com`. The original logic of this plugin doesn't take this into account and would modify an existing one if found, resulting only one single TXT record in this case. So it will always fail for one of the check. New version add one record regardlessly and will only cleanup the record it added. However it is advised to make the wait time a bit longer by setting `--dns-tencentcloud-propagation-seconds`.

### renew seperate certs for `*.abc.com` and `abc.com`

In this case two certs with same txt record are to be checked. However it seems Let's Encrypt cache the DNS record for at most 60 seconds [src1] [src2]. Since dnspod doesn't allow us setting the ttl too small, in this scenario just make the waiting time longer (same option as last one mentioned)

[src1]: https://stackoverflow.com/questions/54654135/letsencrypt-certbot-rejects-dns-txt-record-for-wildcard-certificate
[src2]: https://community.letsencrypt.org/t/allow-changing-the-acme-challenge-txt-record-id/108541
