### ISSUE TITLE
关于权限问题

### ISSUE THREAD

**Issue by hhucqian** [Frefreak/certbot-dns-tencentcloud#4]
如果我新建一个子账户：user1，默认不给任何权限。
在域名的dnspod[控制台中](https://console.dnspod.cn/dns/list)进入对应域名的管理界面，在“权限管理”->"CAM权限管理"中添加子用户user1，这个时候在[腾讯云后台](https://console.cloud.tencent.com/cam)中对应子用户的详情页里面会新增一个dnspod-rw-***的自定义策略，这个时候尝试`certbot renew --dry-run`失败，然后我又尝试给user1直接添加QcloudDNSPodFullAccess策略发现也失败。
我觉得现在给一个QCloudResourceFullAccess策略也不是长久之计啊

**Comment by Frefreak** [comment]
你好，这个插件当前使用的是CNS模块的API，因为当时好像还没有dnspod模块的。我初步测试了一下dnspod的API，没有问题，这几天会把涉及到的调用全部换成dnspod的，到时就只用添加**QcloudDNSPodFullAccess**就可以了。

**Comment by Frefreak** [comment]
我更新了一个版本，但还没上传到pypi。介意有空测试下当前master版本吗。[README](https://github.com/Frefreak/certbot-dns-tencentcloud#:~:text=we%20now%20use%20the%20new%20dnspod%20api%20so%20you%20need%20to%20give%20qclouddnspodfullaccess%20strategy)和changelog我也已经相应更新。

**Comment by Frefreak** [comment]
pypi前几天同步了，issue先关了，如有问题可以reopen。

For future visitors: we switched from cns api to the new dnspod api, and you should use `QcloudDNSPodFullAccess` strategy with your api user's permission from now on.
